### ISSUE TITLE
Empty marker string does not get replaced with empty string for Dropdownbox

### ISSUE THREAD

**Issue by pbrinkho-hsdg** [AludraTest/aludratest#26]
If you use an empty marker (\<EMPTY\>) in your data spreadsheet it should be replaced by an empty string during run-time. In this case GUI actions shall be performed e.g. to empty filled fields, which would not be possible, if you have an empty field in your spreadsheet (would be mapped as null and no action will be performed).  

The empty marker is not recognized and converted for GUI Element Dropdownbox as it is done for e.g. InputField: 

perform().type(elementType, elementName, locator, <b>DataMarkerCheck.convertIfEmpty(text)</b>, taskCompletionTimeout);

Dropdownbox.class:

    /** Selects an entry of this Dropdownbox by its label. If the label is <code>null</code> or marked as null, the operation is
     * not executed. It the label is marked as empty, it will be replaced with "".
     * 
     * @param label Label of the entry to select. */
    public void selectEntry(String label) {
        if (!DataMarkerCheck.isNull(label)) {
            selectEntry(new LabelLocator(label));
        }
    }

    /** Selects an entry of a Dropdownbox by its locator, which must be either a {@link LabelLocator} or an {@link IndexLocator}.
     * 
     * @param optionLocator is a LabelLocator or IndexLocator for identifying the entry to select. If <code>null</code>, no action
     *            is performed. */
    public void selectEntry(OptionLocator optionLocator) {
        if (optionLocator != null) {
            perform().selectDropDownEntry(elementType, elementName, locator, optionLocator, taskCompletionTimeout);
        }
    }

**Comment by falbrech-hsdg** [comment]
Well "at run-time" is a little bit misleading, as the <EMPTY> must be loaded from the spreadsheet and kept in the according String field (there was a confusion regarding this in the past).

It is a little bit tricky that every method has to deal with this marker for itself. Besides of fixing this issue, perhaps we should think about a more central place to deal with this marker. Opinions, ideas?
