### ISSUE TITLE
Rework ElementLocators

### ISSUE THREAD

**Issue by PeterBrinkhoff** [AludraTest/aludratest#51]
Using ElementLocators on Selenium2 is very slow and time consuming because any underlying locator generates a separate Selenium call. Thus it would be nice to rework the implemention of ElementLocators:

Internally they should be combined that there is only one Selenium call to be executed. 
e.g. ( //*[@id="xyz1"] | //*[@id="xyz2"] )

No to loose any information AludraTest should log which id has been used to identify the GUI element.

**Comment by falbrech-hsdg** [comment]
Implemented and verified.
