### ISSUE TITLE
Implement new Test Data concept

### ISSUE THREAD

**Issue by falbrech-hsdg** [AludraTest/aludratest#54]
Currently, AludraTest requires test data to be provided in Excel files with a specific format. These Excel files are hard to maintain, e.g. when attributes are added to or removed from Data classes. 

So we should implement a new Test Data concept. This should provide the following features:

- an internal format, XML based, for storing test data
- a GUI editor for editing test data for data classes, e.g. as an Eclipse plug-in
- a verification mechanism checking consistency of test data (synchronization between data classes and test data)
- an "Excel export" like feature to quickly review test data

Developers should create a data class and ideally click a button to "generate test data file". Then the editor should parse the AludraTest settings for the current project to find the location for test files (e.g. src/main/resources/testdata) and create the required XML file there, if it does not already exist (otherwise, it is loaded and opened for editing).
Afterwards, the GUI editor should pop up and query the user for test data sets for the data file. 

The verification of the data files should ideally also be possible using a Maven plug-in, which would allow for implementing it in a Maven phase before executing the tests.

Please add more required features as comment in this ticket.

**Comment by BjoernKellermann** [comment]
Excel can process XML directly if xsd or dtd is available.

**Comment by falbrech-hsdg** [comment]
Merged feature into master. Eclipse GUI editor is still tested internally.
