### ISSUE TITLE
Add field work to test log (work as summed execution time of all sub elements)

### ISSUE THREAD

**Issue by PeterBrinkhoff** [AludraTest/aludratest#69]
Currently the duration of a testsuite is calculated as difference between start and end time of the first and last child element within the suite. 

Rather than this I would prefer that the duration is calculated as sum of durations of child elements.

**Comment by BjoernKellermann** [comment]
-1 ;)
Duration vs. Work

In most project methods their is a difference between work or effort spent and duration.

Duration is time from earliest sart until later finish.
Work is sum of work of all sub elements.

I strongly recommend changing the request to add field "work" with definition:
Each element shall have a field work.
For tests (leave), work is equal duration as long as their is no other definition based on test steps or test step groups.
For suites (composite), work is the sum of work for all child elements (suites, tests).

**Comment by pbrinkho-hsdg** [comment]
Good point. I will update the request accordingly. 

Just one comment. Tests (without work field) are here meant as the lowest hierarchy level (test configurations). All hierarchy levels above should have the work field instead.

**Comment by falbrech-hsdg** [comment]
Implemented for a long time now.
