### ISSUE TITLE
Configurable logging for aludra commands in perform() action

### ISSUE THREAD

**Issue by PeterBrinkhoff** [AludraTest/aludratest#8]
The logged commands within the test case log are defined by AludraTest. 

It would be helpful to 
- configure the commands that are included in the log OR to just
- allow logging of ALL performed actions such as "isElement..."
  *\* e.g. having a general property <br>_-DALUDRATEST_CONFIG/aludratest/log.all.commands=true_

![command](https://cloud.githubusercontent.com/assets/9377938/5225282/9f4f86a0-76e2-11e4-84d8-d02915a295bb.png)

**Comment by falbrech-hsdg** [comment]
Now possible using log4testing's step filters.
